# Generated by Django 3.0.3 on 2020-03-01 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER',
            fields=[
                ('userId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cardId', models.IntegerField(default=0)),
                ('stuId', models.CharField(max_length=20)),
                ('stuPw', models.CharField(max_length=20)),
                ('cookie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EXPEND',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('expendId', models.IntegerField(default=0)),
                ('expendTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('stuId', models.CharField(max_length=20)),
                ('stuName', models.CharField(max_length=20)),
                ('expendType', models.CharField(max_length=20)),
                ('shopName', models.CharField(max_length=50)),
                ('expendMoney', models.FloatField(default=0)),
                ('vacancy', models.FloatField(default=0)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawExpendData.USER')),
            ],
        ),
    ]
